services:
  - type: web
    name: tesis-accuiculture
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: postgresql://ecosistemasterrestres_x98v_user:o5YdYg9mhlMyPsulbGTOHQ4UwfreU8Jz@dpg-d0uelqemcj7s739k22qg-a/ecosistemasterrestres_x98v
    healthCheckPath: /
    autoDeploy: true
