services:
  - type: web
    name: tesis-accuiculture
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
